spring:
  h2:
    console.settings.trace: false
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: 1000
#      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
    show-sql: true
  datasource:
    hikari:
      auto-commit: false
